<?php
$this->headScript()->prependFile($this->baseUrl().'/js/jquery.bgiframe.min.js');
$this->headScript()->prependFile($this->baseUrl().'/js/jquery.multiSelect.js');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/form-buttons.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/jquery.multiSelect.css');
$this->title = "Member Search";
$this->headTitle($this->title);
?>

<body class="span12" id="memberSearch">
<div>
	
	<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
	<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
	<a href="/public/admin/company">&nbsp;<b>Companies</b></a>
	
<div class="row">
	<form action="<?php echo $this->escape($this->form->getAction()) ?>"
    	method="<?php echo $this->escape($this->form->getMethod()) ?>"
		enctype="multipart/form-data">
</div>

<div class="row"><!-- Start of first row -->
	
<div class="span4">
	<fieldset>
    	<legend></legend>
		<?= $this->form->name ?>
		Search by County
		<select id="county" name="county[]" multiple="multiple" size="5">
		<?php
			foreach ($this->county_list as $county) {
				echo '<option value="' . $county['key'] . '">' . $county['value'] . '</option>';
			}
		?>
		</select>
		<br>
		Search by Region
		<select id="region" name="region[]" multiple="multiple" size="5">
		<?php
			foreach ($this->region_list as $region) {
				echo '<option value="' . $region['key'] . '">' . $region['value'] . '</option>';
			}
		?>
		</select>
		<br>
		Search by Industry Type
		<select id="sector" name="sector[]" multiple="multiple" size="5">
		<?php
			foreach ($this->sector_list as $sector) {
				echo '<option value="' . $sector['key'] . '">' . $sector['value'] . '</option>';
			}
		?>
		</select>
		<br>
		Search by Keyword/s
		<select id="keyword" name="keyword[]" multiple="multiple" size="5">
		<?php
			foreach ($this->keyword_list as $keyword) {
				echo '<option value="' . $keyword['key'] . '">' . $keyword['value'] . '</option>';
			}
		?>
		</select>
		<br>
		Search by Number of Employees
		<select id="numEmployees" name="numEmployees[]" multiple="multiple" size="5">
		<?php
			foreach ($this->number_of_employees_list as $num_employees) {
				echo '<option value="' . $num_employees['key'] . '">' . $num_employees['value'] . '</option>';
			}
		?>
		</select>
		<!--
		<select id="test" name="test[]" multiple="multiple" size="5">
			<option value="option1">Option 1</option>
			<option value="option2">Option 2</option>
		</select>
		-->
	</fieldset>
</div>

<div class="span4">
	<fieldset>
    	<legend></legend>
    	<?= $this->form->search_type ?>
    </fieldset>
</div>

</div><!-- End of first row -->

<div class="row">
	<span class="submit"><?= $this->form->submit ?></span><?= $this->form->cancel ?>
</div>

</form>

</div>
</body>