<?php
$this->headLink()->prependStylesheet($this->baseUrl().'/css/form-buttons.css');
$this->title = "Add Company Info";
$this->headTitle($this->title);
?>

<body class="span12">
<div>

<div class="row">
	
<form action="<?php echo $this->escape($this->form->getAction()) ?>"
   	method="<?php echo $this->escape($this->form->getMethod()) ?>"
	enctype="multipart/form-data">
</div>

	<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
	<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
	<a href="/public/admin/company">&nbsp;<b>Companies</b></a>

<div class="row"><!-- Start of first row -->
	<div class="span6">
		<fieldset>
    		<legend></legend>
			<?= $this->form->current_company_name ?>
			<?= $this->form->company_website ?>
			<?= $this->form->num_employees_sel ?>
			<?= $this->form->sector_sel ?>
			<?= $this->form->previous_company_names ?>
			<?= $this->form->other_websites ?>
		</fieldset>
	</div>
</div><!-- End of first row -->

<div class="row">
	<span class="submit"><?= $this->form->submit ?></span><?= $this->form->cancel ?>
</div>

</form>

</div>
</body>