<?php
$this->headLink()->prependStylesheet($this->baseUrl().'/css/form-buttons.css');
$this->title = "Add social media details";
$this->headTitle($this->title);
$this->member_service->populateFormAddMemSocMedia($this->form);
?>

<body class="span12">
<div>

	<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
	<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
	<a href="/public/admin/company">&nbsp;<b>Companies</b></a>

<div class="row">

<form action="<?php echo $this->escape($this->form->getAction()) ?>"
   	method="<?php echo $this->escape($this->form->getMethod()) ?>"
	enctype="multipart/form-data">
</div>

<div class="row"><!-- Start of first row -->	
	<div class="span4">
		<fieldset>
			<legend></legend>
			<?= $this->form->social_media_linkedin_name ?>
			<?= $this->form->social_media_facebook_name ?>
			<?= $this->form->social_media_skype_id ?>
			<?= $this->form->social_media_twitter_username ?>
			<?= $this->form->social_media_other ?>
		</fieldset>
	</div>
</div><!-- End of first row -->

<div class="row"><!-- start of second row -->
	<span class="submit"><?= $this->form->submit ?></span><?= $this->form->cancel ?>
</div><!-- end of second row -->

</form>

</div>
</body>