<?php
$this->headLink()->prependStylesheet($this->baseUrl().'/css/edit.css');

$c_id = $_GET['c_id']; // get company id

Zend_Session::start();
$company = new Zend_Session_Namespace('company');

if(!isset($company->c_id)) {
	$company->c_id = $c_id;
} else {
	if(isset($c_id) && $c_id != $company->c_id) {
		$company->c_id = $c_id;
	}
}

$referrer = $_SERVER['HTTP_REFERER'];
$referrer = substr( $referrer, strrpos($referrer, '/' )+1); // get everything after last slash

// if we've come from the company page, redirect back to company page
// else redirect back to member edit page
if($referrer == "company") {
	unset($company->referrer);
} else {
	if(isset($company->referrer)) {
		$referrer = $company->referrer;
	} else {
		$referrer = "company";
	}
}

$company_profile = $this->company_tbl->getCompany($company->c_id);
$this->title = "Edit Company: " . '"' . $company_profile['current_company_name'] . '"';
$this->headTitle($this->title);

?>
<body class="span12">
<div>
<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
<a href="/public/admin/company">&nbsp;<b>Companies</b></a>

<!-- ----------------------------------------------------------------- -->
<div class="row">	
	<div class="span12">
		<br>
		<ul id="menu">
			<li><a href="editcompanyinfo?c_id=<?php echo $company->c_id ?>">Company Info</a></li>
			<li><a href="editcompanyoffice?c_id=<?php echo $company->c_id ?>&office_type=head">Head office address</a></li>
    		<li><a href="editcompanyoffice?c_id=<?php echo $company->c_id ?>&office_type=second">Second office address</a></li>
    		<li><a href="editcompanyoffice?c_id=<?php echo $company->c_id ?>&office_type=third">Third office address</a></li>
    		<li><a href="<?php echo $referrer ?>"><i>Done</i></a></li>
		</ul>
	</div>
</div>
<!-- ----------------------------------------------------------------- -->
</div>
</body>