<?php
$this->headLink()->prependStylesheet($this->baseUrl().'/css/form-buttons.css');
$c_id = $_GET['c_id']; // get company id
$this->company_service->populateFormCompInfo($this->form, $c_id);
$company = $this->company_tbl->getCompany($c_id);
$this->title = "Edit info for company: " . '"' . $company['current_company_name'] . '"';
$this->headTitle($this->title);
?>

<body class="span12">
<div>

	<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
	<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
	<a href="/public/admin/company">&nbsp;<b>Companies</b></a>

<div class="row">
	
<form action="<?php echo $this->escape($this->form->getAction()) ?>"
   	method="<?php echo $this->escape($this->form->getMethod()) ?>"
	enctype="multipart/form-data">
</div>

<div class="row"><!-- Start of first row -->
	<div class="span6">
		<fieldset>
    		<legend></legend>
			<?= $this->form->current_company_name ?>
			<?= $this->form->company_website ?>
			<?= $this->form->num_employees_sel ?>
			<?= $this->form->sector_sel ?>
			<?= $this->form->previous_company_names ?>
			<?= $this->form->other_websites ?>
		</fieldset>
	</div>
</div><!-- End of first row -->

<div class="row">
	<span class="submit"><?= $this->form->submit ?></span><?= $this->form->cancel ?>
</div>

</form>

</div>
</body>