<?php
$this->headLink()->prependStylesheet($this->baseUrl().'/css/form-buttons.css');
$m_id = $_GET['m_id'];
$this->form->m_id->setValue($m_id);
$this->title = "Add new Company";
$this->headTitle($this->title);
?>

<body class="span12" id="addCompany">
<div>

	<a href="/public/admin/index">&nbsp;<b>Home</b></a>&nbsp;
	<a href="/public/admin/member">&nbsp;<b>Members</b></a>&nbsp;
	<a href="/public/admin/company">&nbsp;<b>Companies</b></a>

<div class="row">
	<form action="<?php echo $this->escape($this->form->getAction()) ?>"
    	method="<?php echo $this->escape($this->form->getMethod()) ?>"
		enctype="multipart/form-data">
</div>

<div class="row"><!-- Start of first row -->
	
<div class="span3">
	<fieldset>
    	<legend>Company Info</legend>
		<?= $this->form->company_type ?>
		<?= $this->form->company_sel ?>
		<?= $this->form->current_company_name ?>
		<?= $this->form->company_website ?>
		<?= $this->form->num_employees_sel ?>
		<?= $this->form->sector_sel ?>
		<?= $this->form->previous_company_names ?>
		<?= $this->form->other_websites ?>
	</fieldset>
</div>

<div class="span3">
	<fieldset>
    	<legend>Head Office Address</legend>
		<?= $this->form->address_1 ?>
		<?= $this->form->address_2 ?>
		<?= $this->form->address_3 ?>
		<?= $this->form->postcode ?>
		<?= $this->form->county_sel ?>
		<?= $this->form->country_sel ?>
		<?= $this->form->contact_number ?>
	</fieldset>
</div>

</div><!-- End of first row -->

<div class="row">
	<span class="submit"><?= $this->form->submit ?></span>
	<br>
	<input type="button" id="cancel_btn_edit_member" name="cancel_btn_edit_member" value="cancel" />
</div>

</form>

</div>
</body>